import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
// import {light} from '@clerk/themes'
import { LeftsideBar } from '../../components/shared/LeftsideBar' 
import { Bottombar } from '../../components/shared/Bottombar'
import { RightsideBar } from '../../components/shared/RightsideBar'
import { TopBar } from '../../components/shared/TopBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mock Threads',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body 
          className={inter.className}
          suppressHydrationWarning={true}
        >
          <TopBar />

          <main className="flex flex-row">
            <LeftsideBar />

            <section className="main-container">
              <div className="w-full max-w-4xl">
                {children}
              </div> 
            </section>

            <RightsideBar />
          </main>

          <Bottombar />
        </body>
      </html>
    </ClerkProvider>
  )
}
