import './globals.css'
import {Navbar} from '@/components/ui/Navbar'
import {Providers} from '@/components/Providers'
import { Inter } from 'next/font/google'
import {Toaster} from '@/components/ui/Toaster'
import {cn} from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mock Reddit',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  authModal
}: {
  children: React.ReactNode,
  authModal: React.ReactNode
}) {
  return (
    <html 
      lang="en" 
      className={cn(
        'bg-white text-slate-900 antialiased light',
        inter.className
      )}>
      <body 
        className='min-h-screen pt-12 bg-slate-50 antialiased' 
        suppressHydrationWarning={true}
      >
        <Providers>
          <Navbar />
          {authModal}

          <div className="container max-w-7xl mx-auto h-full pt-12">
            {children} 
          </div> 
        </Providers>
        
        <Toaster />
      </body>
    </html>
  )
}
