import React, { ReactNode } from 'react'
import type {Metadata} from  'next'
import {Inter} from 'next/font/google'
import {ClerkProvider} from '@clerk/nextjs'
// import {light} from '@clerk/themes'
import '../globals.css'

const inter = Inter({
	subsets: ['latin']
})

export const metatdata: Metadata = {
	title: 'Auth',
	description: 'Generated by create next app'
}

const RootLayout = ({children}: {children: ReactNode}) => {
	return (
		<ClerkProvider>
				<html lang='en'>
					<body 
						className={`${inter.className} bg-dark-1`}
						suppressHydrationWarning={true}
					>
						<main className="container mx-auto">
							<div className="flex items-start justify-center min-h-screen">
								<div className="mt-20">
									{children}
								</div>
							</div>
          </main>
					</body>
				</html>
		</ClerkProvider>
	)
}

export default RootLayout